data:
  image: cogniteev/echo
  command: echo 'Data Container for Thumbor'
  volumes:
    - /data/thumbor/data:/data
    - /data/thumbor/logs:/logs
thumbor:
  image: apsl/thumbor-multiprocess:latest
  volumes_from:
    - data
  #ports:
    #- "80:80" # thumbor port
  environment:
    ALLOW_UNSAFE_URL: "True"
    UPLOAD_ENABLED: "True"
    SECURITY_KEY: "SECURIZE_ME"
    # DETECTORS: "['thumbor.detectors.queued_detector.queued_complete_detector',]"
    # AWS_ACCESS_KEY:  # put your AWS_ACCESS_KEY here
    # AWS_SECRET_KEY:  # put your AWS_SECRET_KEY here
    # STORAGE: thumbor.storages.mixed_storage
    # STORAGE_BUCKET: storage-bucket-name
    # UPLOAD_PHOTO_STORAGE: thumbor_aws.storages.s3_storage
    # MIXED_STORAGE_FILE_STORAGE: thumbor_aws.storages.s3_storage
    RESULT_STORAGE: thumbor.result_storages.file_storage
    RESULT_STORAGE_FILE_STORAGE_ROOT_PATH: "/data/result_storage"
    # REDIS_STORAGE_SERVER_HOST: redis
    # REDIS_STORAGE_SERVER_PORT: 6379
    # REDIS_STORAGE_SERVER_DB: 0
    # REDIS_QUEUE_SERVER_HOST: redis
    # REDIS_QUEUE_SERVER_PORT: 6379
    # REDIS_QUEUE_SERVER_DB: 0
    # MIXED_STORAGE_DETECTOR_STORAGE: thumbor.storages.redis_storage
    # SENTRY_DSN_URL: # put your sentry enpoint here
    THUMBOR_NUM_PROCESSES: 3
  # links:
    # - redis:redis
upload:
  build: upload
upload_php_fpm:
  build: php-fpm
  environment:
    THUMBOR_HOST: "http://thumbor"
    THUMBOR_PROXY: "http://dockerhost"
    THUMBOR_SECRET_KEY: "SECURIZE_ME"
  volumes_from:
    - upload
  links:
    - thumbor:thumbor
nginx:
  build: nginx
  links:
    - thumbor:thumbor
    - upload_php_fpm:php-fpm
  volumes_from:
    - data
    - upload
  ports:
    - "80:80" # nginx cache port (with failover to thumbor)
  hostname: nginx
# remotecv:
  # image: apsl/remotecv:latest
  # links:
    # - redis:redis
  # environment:
    # REDIS_HOST: redis
    # REDIS_PORT: 6379
    # REDIS_DATABASE: 0
# redis:
  # image: redis:latest
